-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.24-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL version:             7.0.0.4160
-- Date/time:                    2013-01-24 14:23:15
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for dummy
CREATE DATABASE IF NOT EXISTS `dummy` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `dummy`;


-- Dumping structure for table dummy.dummy
DROP TABLE IF EXISTS `dummy`;
CREATE TABLE IF NOT EXISTS `dummy` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT,
  `inf1` varchar(64) DEFAULT NULL,
  `inf2` varchar(64) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=103 DEFAULT CHARSET=utf8;

-- Dumping data for table dummy.dummy: ~101 rows (approximately)
/*!40000 ALTER TABLE `dummy` DISABLE KEYS */;
INSERT INTO `dummy` (`id`, `inf1`, `inf2`, `created_at`, `updated_at`) VALUES
	(1, 'Row1_Col1', 'Row1_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(2, 'Row2_Col1', 'Row2_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(3, 'Row3_Col1', 'Row3_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(4, 'Row4_Col1', 'Row4_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(5, 'Row5_Col1', 'Row5_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(6, 'Row6_Col1', 'Row6_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(7, 'Row7_Col1', 'Row7_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(8, 'Row8_Col1', 'Row8_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(9, 'Row9_Col1', 'Row9_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(10, 'Row10_Col1', 'Row10_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(11, 'Row11_Col1', 'Row11_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(12, 'Row12_Col1', 'Row12_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(13, 'Row13_Col1', 'Row13_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(14, 'Row14_Col1', 'Row14_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(15, 'Row15_Col1', 'Row15_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(16, 'Row16_Col1', 'Row16_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(17, 'Row17_Col1', 'Row17_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(18, 'Row18_Col1', 'Row18_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(19, 'Row19_Col1', 'Row19_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(20, 'Row20_Col1', 'Row20_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(21, 'Row21_Col1', 'Row21_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(22, 'Row22_Col1', 'Row22_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(23, 'Row23_Col1', 'Row23_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(24, 'Row24_Col1', 'Row24_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(25, 'Row25_Col1', 'Row25_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(26, 'Row26_Col1', 'Row26_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(27, 'Row27_Col1', 'Row27_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(28, 'Row28_Col1', 'Row28_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(29, 'Row29_Col1', 'Row29_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(30, 'Row30_Col1', 'Row30_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(31, 'Row31_Col1', 'Row31_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(32, 'Row32_Col1', 'Row32_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(33, 'Row33_Col1', 'Row33_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(34, 'Row34_Col1', 'Row34_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(35, 'Row35_Col1', 'Row35_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(36, 'Row36_Col1', 'Row36_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(37, 'Row37_Col1', 'Row37_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(38, 'Row38_Col1', 'Row38_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(39, 'Row39_Col1', 'Row39_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(40, 'Row40_Col1', 'Row40_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(41, 'Row41_Col1', 'Row41_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(42, 'Row42_Col1', 'Row42_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(43, 'Row43_Col1', 'Row43_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(44, 'Row44_Col1', 'Row44_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(45, 'Row45_Col1', 'Row45_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(46, 'Row46_Col1', 'Row46_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(47, 'Row47_Col1', 'Row47_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(48, 'Row48_Col1', 'Row48_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(49, 'Row49_Col1', 'Row49_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(50, 'Row50_Col1', 'Row50_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(51, 'Row51_Col1', 'Row51_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(52, 'Row52_Col1', 'Row52_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(53, 'Row53_Col1', 'Row53_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(54, 'Row54_Col1', 'Row54_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(55, 'Row55_Col1', 'Row55_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(56, 'Row56_Col1', 'Row56_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(57, 'Row57_Col1', 'Row57_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(58, 'Row58_Col1', 'Row58_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(59, 'Row59_Col1', 'Row59_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(60, 'Row60_Col1', 'Row60_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(61, 'Row61_Col1', 'Row61_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(62, 'Row62_Col1', 'Row62_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(63, 'Row63_Col1', 'Row63_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(64, 'Row64_Col1', 'Row64_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(65, 'Row65_Col1', 'Row65_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(66, 'Row66_Col1', 'Row66_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(67, 'Row67_Col1', 'Row67_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(68, 'Row68_Col1', 'Row68_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(69, 'Row69_Col1', 'Row69_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(70, 'Row70_Col1', 'Row70_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(71, 'Row71_Col1', 'Row71_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(72, 'Row72_Col1', 'Row72_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(73, 'Row73_Col1', 'Row73_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(74, 'Row74_Col1', 'Row74_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(75, 'Row75_Col1', 'Row75_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(76, 'Row76_Col1', 'Row76_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(77, 'Row77_Col1', 'Row77_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(78, 'Row78_Col1', 'Row78_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(79, 'Row79_Col1', 'Row79_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(80, 'Row80_Col1', 'Row80_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(81, 'Row81_Col1', 'Row81_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(82, 'Row82_Col1', 'Row82_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(83, 'Row83_Col1', 'Row83_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(84, 'Row84_Col1', 'Row84_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(85, 'Row85_Col1', 'Row85_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(86, 'Row86_Col1', 'Row86_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(87, 'Row87_Col1', 'Row87_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(88, 'Row88_Col1', 'Row88_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(89, 'Row89_Col1', 'Row89_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(90, 'Row90_Col1', 'Row90_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(91, 'Row91_Col1', 'Row91_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(92, 'Row92_Col1', 'Row92_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(93, 'Row93_Col1', 'Row93_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(94, 'Row94_Col1', 'Row94_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(95, 'Row95_Col1', 'Row95_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(96, 'Row96_Col1', 'Row96_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(97, 'Row97_Col1', 'Row97_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(98, 'Row98_Col1', 'Row98_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(99, 'Row99_Col1', 'Row99_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(100, 'Row100_Col1', 'Row100_Col2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
/*!40000 ALTER TABLE `dummy` ENABLE KEYS */;

